import {z} from 'zod';
import {env} from 'cloudflare:workers';
import {all,first,run,db,user,requireRole,cartOwner,mergeCart,body,protect,json,boundary,HttpError,id,now,productProjection,audit,notify,config} from '@/lib/server';
import {addressSchema,productSchema,checkoutSchema} from '@/lib/validation';
import {cart,quote,createOrder,cancelDemoOrder,paymentOptions} from '@/lib/commerce';
import {beginPayment} from '@/lib/payments';
import {seedDemo} from '@/lib/catalog';
export const dynamic='force-dynamic';
type Context={params:Promise<{path:string[]}>};
export async function GET(req:Request,ctx:Context){return boundary(async()=>{const {path}=await ctx.params;const [resource,key]=path;const u=new URL(req.url);if(resource==='me'){const who=await user(false);if(who)await mergeCart(who.id);return json({user:who,payments:paymentOptions()})}if(resource==='product'){await seedDemo();const p=await first('SELECT '+productProjection+' FROM products p WHERE p.id=? AND p.active=1',key);if(!p)throw new HttpError(404,'That product was not found.');const reviews=await all('SELECT r.*,u.name FROM reviews r JOIN users u ON u.id=r.userId WHERE productId=? ORDER BY createdAt DESC LIMIT 50',key);return json({product:p,reviews})}if(resource==='cart'){const owner=await cartOwner();return json(await quote(owner,u.searchParams.get('coupon')||'',u.searchParams.get('country')||'IN'))}if(resource==='media'){if(!key||!/^[a-f0-9-]+\.(jpg|png|webp)$/.test(key))throw new HttpError(404,'Image not found.');const file=await env.BUCKET?.get(key);if(!file)throw new HttpError(404,'Image not found.');return new Response(file.body,{headers:{'Content-Type':file.httpMetadata?.contentType||'image/jpeg','Cache-Control':'public,max-age=31536000,immutable','X-Content-Type-Options':'nosniff'}})}const who=(await user())!;
if(resource==='wishlist')return json({items:await all('SELECT '+productProjection+' FROM wishlists w JOIN products p ON p.id=w.productId WHERE w.userId=? AND p.active=1',who.id)});
if(resource==='addresses')return json({items:await all('SELECT * FROM addresses WHERE userId=?',who.id)});
if(resource==='notifications')return json({items:await all('SELECT * FROM notifications WHERE userId=? ORDER BY createdAt DESC LIMIT 100',who.id)});
if(resource==='orders'){const items=await all('SELECT * FROM orders WHERE userId=? ORDER BY createdAt DESC LIMIT 100',who.id);for(const order of items){order.items=await all('SELECT * FROM order_items WHERE orderId=?',order.id);order.returnRequest=await first('SELECT * FROM returns WHERE orderId=?',order.id)}return json({items})}
if(resource==='seller-application')return json({application:await first('SELECT * FROM seller_applications WHERE userId=?',who.id)});
if(resource==='dashboard'){await requireRole('seller','admin');const admin=who.role==='admin';const products=await all('SELECT '+productProjection+' FROM products p '+(admin?'':'WHERE sellerId=? ')+'ORDER BY createdAt DESC LIMIT 200',...(admin?[]:[who.id]));const items=await all('SELECT i.*,o.status,o.paymentStatus,o.createdAt FROM order_items i JOIN orders o ON o.id=i.orderId '+(admin?'':'WHERE i.sellerId=? ')+'ORDER BY o.createdAt DESC LIMIT 200',...(admin?[]:[who.id]));const revenue=await first('SELECT COALESCE(SUM(i.price*i.quantity),0) revenue FROM order_items i JOIN orders o ON o.id=i.orderId WHERE o.paymentStatus=\'paid\' '+(admin?'':'AND i.sellerId=?'),...(admin?[]:[who.id]));return json({products,items,revenue:revenue.revenue,applications:admin?await all('SELECT a.*,u.email FROM seller_applications a JOIN users u ON u.id=a.userId ORDER BY createdAt DESC LIMIT 100'):[],returns:admin?await all('SELECT r.*,o.paymentProvider,o.total FROM returns r JOIN orders o ON o.id=r.orderId ORDER BY createdAt DESC LIMIT 100'):[],coupons:admin?await all('SELECT * FROM coupons'):[],messages:admin?await all('SELECT * FROM messages ORDER BY createdAt DESC LIMIT 100'):[],outbox:admin?await all('SELECT id,subject,status,createdAt FROM outbox ORDER BY createdAt DESC LIMIT 100'):[]})}throw new HttpError(404,'Endpoint not found.')})}
export async function POST(req:Request,ctx:Context){return boundary(async()=>{await protect(req);const{path}=await ctx.params;const[resource,key]=path;
if(resource==='cart'){const input=await body(req,z.object({productId:z.string().min(1).max(100),quantity:z.number().int().min(0).max(20),replace:z.boolean().default(false)}));const owner=await cartOwner();await seedDemo();const p=await first('SELECT * FROM products WHERE id=? AND active=1',input.productId);if(!p)throw new HttpError(404,'Product not found.');if(input.quantity===0){await run('DELETE FROM cart_items WHERE owner=? AND productId=?',owner,p.id);return json({ok:true})}const old=await first('SELECT quantity FROM cart_items WHERE owner=? AND productId=?',owner,p.id);const qty=input.replace?input.quantity:(old?.quantity||0)+input.quantity;if(qty>20||qty>p.stock)throw new HttpError(409,'That quantity is not available.');await run('INSERT INTO cart_items (owner,productId,quantity) VALUES (?,?,?) ON CONFLICT(owner,productId) DO UPDATE SET quantity=excluded.quantity',owner,p.id,qty);return json({ok:true})}
const who=(await user())!;
if(resource==='wishlist'){const input=await body(req,z.object({productId:z.string().max(100)}));const exists=await first('SELECT id FROM products WHERE id=? AND active=1',input.productId);if(!exists)throw new HttpError(404,'Product not found.');if(await first('SELECT productId FROM wishlists WHERE userId=? AND productId=?',who.id,input.productId))await run('DELETE FROM wishlists WHERE userId=? AND productId=?',who.id,input.productId);else await run('INSERT INTO wishlists (userId,productId) VALUES (?,?)',who.id,input.productId);return json({ok:true})}
if(resource==='addresses'){const input=await body(req,addressSchema);const addressId=id();await run('INSERT INTO addresses (id,userId,name,phone,line1,city,state,postalCode,country) VALUES (?,?,?,?,?,?,?,?,?)',addressId,who.id,input.name,input.phone,input.line1,input.city,input.state,input.postalCode,input.country);return json({id:addressId},201)}
if(resource==='checkout'){const input=await body(req,checkoutSchema);const options=paymentOptions();if(!options[input.provider])throw new HttpError(503,'This payment method is not configured.');await mergeCart(who.id);const order=await createOrder(who.id,input);const payment=await beginPayment(order);return json({orderId:order.id,...payment},201)}
if(resource==='pay'){const order=await first('SELECT * FROM orders WHERE id=? AND userId=?',key,who.id);if(!order)throw new HttpError(404,'Order not found.');return json(await beginPayment(order))}
if(resource==='cancel'){const order=await first('SELECT * FROM orders WHERE id=? AND userId=?',key,who.id);if(!order)throw new HttpError(404,'Order not found.');await cancelDemoOrder(order);return json({ok:true})}
if(resource==='reviews'){const input=await body(req,z.object({productId:z.string().max(100),rating:z.number().int().min(1).max(5),body:z.string().trim().min(10).max(2000)}));const purchased=await first('SELECT i.id FROM order_items i JOIN orders o ON o.id=i.orderId WHERE i.productId=? AND o.userId=? AND o.status=\'delivered\'',input.productId,who.id);if(!purchased)throw new HttpError(403,'Reviews open after your order is delivered.');await run('INSERT INTO reviews (id,userId,productId,rating,body,createdAt) VALUES (?,?,?,?,?,?) ON CONFLICT(userId,productId) DO UPDATE SET rating=excluded.rating,body=excluded.body',id(),who.id,input.productId,input.rating,input.body,now());return json({ok:true})}
if(resource==='returns'){const input=await body(req,z.object({orderId:z.string().uuid(),reason:z.string().trim().min(10).max(1000)}));const order=await first('SELECT * FROM orders WHERE id=? AND userId=?',input.orderId,who.id);if(!order||order.status!=='delivered'||!order.deliveredAt||Date.now()-Date.parse(order.deliveredAt)>7*86400000)throw new HttpError(400,'Returns can be requested within 7 days of delivery.');if(await first('SELECT id FROM returns WHERE orderId=?',order.id))throw new HttpError(409,'A return request already exists.');await run('INSERT INTO returns (id,orderId,userId,reason,createdAt) VALUES (?,?,?,?,?)',id(),order.id,who.id,input.reason,now());await notify(who.id,'Your return request is awaiting review.');return json({ok:true},201)}
if(resource==='notifications'){await run('UPDATE notifications SET read=1 WHERE userId=?',who.id);return json({ok:true})}
if(resource==='contact'){const input=await body(req,z.object({subject:z.string().trim().min(3).max(150),body:z.string().trim().min(10).max(4000)}));await run('INSERT INTO messages (id,userId,subject,body,createdAt) VALUES (?,?,?,?,?)',id(),who.id,input.subject,input.body,now());return json({ok:true},201)}
if(resource==='seller-application'){const input=await body(req,z.object({storeName:z.string().trim().min(3).max(100),description:z.string().trim().min(20).max(2000)}));if(await first('SELECT id FROM seller_applications WHERE userId=?',who.id))throw new HttpError(409,'You already have an application. Contact support for changes.');await run('INSERT INTO seller_applications (id,userId,storeName,description,createdAt) VALUES (?,?,?,?,?)',id(),who.id,input.storeName,input.description,now());return json({ok:true},201)}
if(resource==='products'){await requireRole('seller','admin');const input=await body(req,productSchema);if(key){const product=await first('SELECT * FROM products WHERE id=?',key);if(!product||(who.role!=='admin'&&product.sellerId!==who.id))throw new HttpError(403,'You cannot edit this product.');await run('UPDATE products SET name=?,brand=?,category=?,description=?,price=?,comparePrice=?,stock=?,image=?,badge=?,active=? WHERE id=?',input.name,input.brand,input.category,input.description,input.price,input.comparePrice,input.stock,input.image,input.badge,input.active,key)}else{const productId=id();await run('INSERT INTO products (id,sellerId,name,brand,category,description,price,comparePrice,stock,image,badge,active,createdAt) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',productId,who.id,input.name,input.brand,input.category,input.description,input.price,input.comparePrice,input.stock,input.image,input.badge,input.active,now())}await audit(who.id,'product.save',key||'new');return json({ok:true})}
if(resource==='upload'){await requireRole('seller','admin');if(!env.BUCKET)throw new HttpError(503,'Image storage is unavailable.');const length=Number(req.headers.get('content-length')||0);if(length>5*1024*1024)throw new HttpError(413,'Images must be smaller than 5 MB.');const reader=req.body?.getReader();if(!reader)throw new HttpError(400,'Image is required.');const chunks:Uint8Array[]=[];let size=0;while(true){const r=await reader.read();if(r.done)break;size+=r.value.length;if(size>5*1024*1024){await reader.cancel();throw new HttpError(413,'Images must be smaller than 5 MB.')}chunks.push(r.value)}const bytes=new Uint8Array(size);let pos=0;for(const c of chunks){bytes.set(c,pos);pos+=c.length}const png=bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71;const jpg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255;const webp=new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP';if(!png&&!jpg&&!webp)throw new HttpError(400,'Upload a JPEG, PNG, or WebP image.');const ext=png?'png':jpg?'jpg':'webp';const name=id()+'.'+ext;await env.BUCKET.put(name,bytes,{httpMetadata:{contentType:'image/'+(jpg?'jpeg':ext)}});return json({url:'/api/media/'+name},201)}
await requireRole('admin');
if(resource==='approve-seller'){const input=await body(req,z.object({applicationId:z.string().uuid(),approve:z.boolean()}));const application=await first('SELECT * FROM seller_applications WHERE id=? AND status=\'pending\'',input.applicationId);if(!application)throw new HttpError(404,'Pending application not found.');await db().batch([db().prepare('UPDATE seller_applications SET status=? WHERE id=?').bind(input.approve?'approved':'rejected',application.id),db().prepare('UPDATE users SET role=? WHERE id=? AND role=\'customer\'').bind(input.approve?'seller':'customer',application.userId)]);await audit(who.id,'seller.review',application.id);await notify(application.userId,input.approve?'Your seller application was approved. Your dashboard is ready.':'Your seller application was not approved. Please contact support.');return json({ok:true})}
if(resource==='order-status'){const input=await body(req,z.object({orderId:z.string().uuid(),status:z.enum(['shipped','delivered']),tracking:z.string().trim().max(150).default('')}));const order=await first('SELECT * FROM orders WHERE id=?',input.orderId);const previous=input.status==='shipped'?'processing':'shipped';if(!order||order.status!==previous||!['paid','simulated'].includes(order.paymentStatus))throw new HttpError(409,'This order cannot move to that status.');if(input.status==='shipped'&&!input.tracking)throw new HttpError(400,'Enter a tracking reference.');await run('UPDATE orders SET status=?,tracking=?,deliveredAt=? WHERE id=? AND status=?',input.status,input.tracking||order.tracking,input.status==='delivered'?now():null,order.id,previous);await notify(order.userId,'Your order is '+input.status+'.');await audit(who.id,'order.'+input.status,order.id);return json({ok:true})}
if(resource==='return-status'){const input=await body(req,z.object({returnId:z.string().uuid(),status:z.enum(['approved','rejected','received','refund_pending'])}));const r=await first('SELECT * FROM returns WHERE id=?',input.returnId);const transitions:Record<string,string[]>= {requested:['approved','rejected'],approved:['received'],received:['refund_pending']};if(!r||!transitions[r.status]?.includes(input.status))throw new HttpError(409,'Invalid return transition.');await run('UPDATE returns SET status=? WHERE id=? AND status=?',input.status,r.id,r.status);await notify(r.userId,'Return status: '+input.status.replaceAll('_',' ')+'.');await audit(who.id,'return.'+input.status,r.id);return json({ok:true})}
if(resource==='coupons'){const input=await body(req,z.object({code:z.string().regex(/^[A-Z0-9]{3,20}$/),percent:z.number().int().min(1).max(75),minimum:z.number().int().min(0),maximum:z.number().int().min(100),expiresAt:z.string().datetime(),active:z.number().int().min(0).max(1)}));await run('INSERT INTO coupons (code,percent,minimum,maximum,expiresAt,active) VALUES (?,?,?,?,?,?) ON CONFLICT(code) DO UPDATE SET percent=excluded.percent,minimum=excluded.minimum,maximum=excluded.maximum,expiresAt=excluded.expiresAt,active=excluded.active',input.code,input.percent,input.minimum,input.maximum,input.expiresAt,input.active);await audit(who.id,'coupon.save',input.code);return json({ok:true})}
throw new HttpError(404,'Endpoint not found.')})}
export async function DELETE(req:Request,ctx:Context){return boundary(async()=>{await protect(req);const who=(await user())!;const{path}=await ctx.params;if(path[0]!=='addresses')throw new HttpError(404,'Endpoint not found.');await run('DELETE FROM addresses WHERE id=? AND userId=?',path[1],who.id);return json({ok:true})})}
