'use client';
import {useEffect,useState} from 'react';
import {toast} from 'sonner';
import {ArrowUpRight} from 'lucide-react';
import {Shell,api} from './storefront';
import {Title,Gate} from './commerce-pages';
import {pages} from '@/lib/content';
import {categories} from '@/lib/types';
export default function PublicPage({slug}:{slug:string}){if(slug==='categories')return <Shell><Title title="Find your corner of NOVA."/><div className="grid">{categories.slice(1).map((c,i)=><a className="article-card" href={'/shop?category='+encodeURIComponent(c)} key={c}><span className="eyebrow">0{i+1} / THE COLLECTION</span><h2>{c}</h2><ArrowUpRight/></a>)}</div></Shell>;if(slug==='contact')return <Shell><Title title="Let’s talk." sub="An order question, a brand introduction, or a little feedback. We’re listening."/><Gate>{()=> <Contact/>}</Gate></Shell>;if(slug==='seller-onboarding')return <Shell><Title title="Your brand. A bigger world." sub="Bring your independent spirit to NOVA MARKET."/><div className="stats">{[['01','Tell your story'],['02','Get approved'],['03','Make your first sale']].map(([n,t])=><div className="panel" key={n}><span className="eyebrow">{n}</span><h3>{t}</h3></div>)}</div><Gate>{u=>u.role!=='customer'?<div className="panel"><h2>You’re ready to build.</h2><a className="btn" href={u.role==='admin'?'/admin':'/seller'}>Open your dashboard <ArrowUpRight/></a></div>:<SellerApplication/>}</Gate></Shell>;const page=pages[slug];if(!page)return <Shell><Title title="That page wandered off."/><a className="btn" href="/shop">Back to the good finds</a></Shell>;return <Shell><Title title={page.title} sub={page.intro}/><div className={slug==='blog'?'grid':'prose'}>{page.sections.map(([heading,text])=><section key={heading} className={slug==='blog'?'article-card':''}><h2>{heading}</h2><p>{text}</p></section>)}</div>{['about','services','blog'].includes(slug)&&<a href="/shop" className="btn" style={{marginTop:25}}>Discover the collection <ArrowUpRight/></a>}</Shell>}
function Contact(){const[busy,setBusy]=useState(false),[done,setDone]=useState(false);return <div className="two-col"><form className="panel stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await api('contact',Object.fromEntries(f));setDone(true)}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}}><h3>Send us a message</h3>{done?<div className="notice" role="status">Message saved. The marketplace support team can review it in the admin dashboard.</div>:<><label>Subject<input name="subject" required minLength={3} maxLength={150}/></label><label>How can we help?<textarea name="body" required minLength={10} maxLength={4000}/></label><button className="btn" disabled={busy}>{busy?'Sending…':'Send message'}</button></>}</form><div className="panel"><h3>A little direction</h3><p>For order questions, include your order reference. Please never send card details, passwords, or identity documents.</p><div className="stack"><a href="/faq">Frequently asked questions ↗</a><a href="/shipping">Delivery information ↗</a><a href="/returns">Returns and refunds ↗</a></div></div></div>}
function SellerApplication(){const[application,setApplication]=useState<any>(),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);const load=()=>api('seller-application').then(d=>{setApplication(d.application);setLoaded(true)}).catch(e=>toast.error(e.message));useEffect(()=>{load()},[]);if(!loaded)return <p>Loading your application…</p>;if(application)return <div className="panel"><span className="status">{application.status}</span><h2>{application.storeName}</h2><p>Your application is {application.status}. Check your account notifications for updates.</p></div>;return <form className="panel stack prose" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('seller-application',Object.fromEntries(new FormData(e.currentTarget)));toast.success('Application submitted');load()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}}><h3>Introduce your brand</h3><label>Store name<input name="storeName" required minLength={3} maxLength={100}/></label><label>What do you make or sell?<textarea name="description" required minLength={20} maxLength={2000}/></label><p className="small">Applications are reviewed by a marketplace administrator. Payment settlement and identity verification must be completed separately before live selling.</p><button className="btn" disabled={busy}>{busy?'Submitting…':'Apply to sell'}</button></form>}
